trainer: forces

dataset:
  - src: ./test_data
    normalize_labels: False

logger: tensorboard

task:
  dataset: trajectory_lmdb
  description: "minimal test"
  type: regression
  metric: mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True
