includes:
- base.yml

model:
  name: schnet
  hidden_channels: 1024
  num_filters: 256
  num_interactions: 5
  num_gaussians: 200
  cutoff: 6.0
  use_pbc: True

optim:
  batch_size: 20
  eval_batch_size: 20
  eval_every: 10000
  num_workers: 0
  lr_initial: 0.0001
  lr_gamma: 0.1
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 100000
  warmup_steps: 100000
  warmup_factor: 0.2
  max_epochs: 15
  force_coefficient: 30
